//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janson.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutTBL
    {
        public int ID { get; set; }
        public string icerik { get; set; }
        public string icerik2 { get; set; }
        public string photo { get; set; }
    }
}
