//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janson.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogTBL()
        {
            this.MesageBlogTBL = new HashSet<MesageBlogTBL>();
        }
    
        public int ID { get; set; }
        public string Photo { get; set; }
        public string Tarih { get; set; }
        public string Baslik { get; set; }
        public string icerik { get; set; }
        public string Olusturan { get; set; }
        public string Category { get; set; }
        public string Tag { get; set; }
        public string OlusturanYorum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesageBlogTBL> MesageBlogTBL { get; set; }
    }
}
