//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janson.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienceTBL
    {
        public int ID { get; set; }
        public string baslik { get; set; }
        public string Aralık { get; set; }
        public string Link { get; set; }
        public string LinkYolu { get; set; }
    }
}
