//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janson.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesageBlogTBL
    {
        public int ID { get; set; }
        public string Photo { get; set; }
        public string İsim { get; set; }
        public string CreateAt { get; set; }
        public string Mail { get; set; }
        public string icerik { get; set; }
        public Nullable<int> BlogID { get; set; }
    
        public virtual BlogTBL BlogTBL { get; set; }
    }
}
