//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janson.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JonsonDbMvcEntities : DbContext
    {
        public JonsonDbMvcEntities()
            : base("name=JonsonDbMvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutTBL> AboutTBL { get; set; }
        public virtual DbSet<AdminTbl> AdminTbl { get; set; }
        public virtual DbSet<ExperienceTBL> ExperienceTBL { get; set; }
        public virtual DbSet<MainTBL> MainTBL { get; set; }
        public virtual DbSet<PhotoTbl> PhotoTbl { get; set; }
        public virtual DbSet<AboutpartTbl> AboutpartTbl { get; set; }
        public virtual DbSet<HobilerTBL> HobilerTBL { get; set; }
        public virtual DbSet<MessageTbl> MessageTbl { get; set; }
    }
}
